# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a15tcsg324-2L

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/lenovo/Desktop/comeon/blue.cache/wt [current_project]
set_property parent.project_path C:/Users/lenovo/Desktop/comeon/blue.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files -quiet C:/Users/lenovo/Desktop/comeon/blue.runs/clk_wiz_0_synth_1/clk_wiz_0.dcp
set_property used_in_implementation false [get_files C:/Users/lenovo/Desktop/comeon/blue.runs/clk_wiz_0_synth_1/clk_wiz_0.dcp]
read_verilog -library xil_defaultlib {
  C:/Users/lenovo/Desktop/comeon/blue.srcs/sources_1/new/pwm.v
  C:/Users/lenovo/Desktop/comeon/blue.srcs/sources_1/new/sonic_detect.v
  C:/Users/lenovo/Desktop/comeon/blue.srcs/sources_1/new/smg_ip_model.v
  C:/Users/lenovo/Desktop/comeon/blue.srcs/sources_1/new/uart_rx.v
  C:/Users/lenovo/Desktop/comeon/blue.srcs/sources_1/new/uart_tx.v
  C:/Users/lenovo/Desktop/comeon/blue.srcs/sources_1/new/speed_select_rx.v
  C:/Users/lenovo/Desktop/comeon/blue.srcs/sources_1/new/forward.v
  C:/Users/lenovo/Desktop/comeon/blue.srcs/sources_1/new/sonic.v
  C:/Users/lenovo/Desktop/comeon/blue.srcs/sources_1/new/uart_top.v
  C:/Users/lenovo/Desktop/comeon/blue.srcs/sources_1/new/state.v
}
read_xdc C:/Users/lenovo/Desktop/comeon/blue.srcs/constrs_1/new/state.xdc
set_property used_in_implementation false [get_files C:/Users/lenovo/Desktop/comeon/blue.srcs/constrs_1/new/state.xdc]

synth_design -top state -part xc7a15tcsg324-2L
write_checkpoint -noxdef state.dcp
catch { report_utilization -file state_utilization_synth.rpt -pb state_utilization_synth.pb }
