set_property SRC_FILE_INFO {cfile:C:/Users/lenovo/Desktop/comeon/blue.srcs/constrs_1/new/state.xdc rfile:../../../blue.srcs/constrs_1/new/state.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets blue/instance_name/inst/clk_in1_clk_wiz_0]
set_property src_info {type:XDC file:1 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets clk_IBUF]
